[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mobile_traffic"
version = "0.1.0"
authors = [{name = "Andrea Musso"}]
requires-python = ">=3.7"
dynamic = ["dependencies"]
dependencies = {file = ["requirements.txt"]}